DROP DATABASE SWFAREREDUCERDB;

START TRANSACTION;

/* ******************************** CREATE DATABASE ******************************** */

CREATE DATABASE IF NOT EXISTS SWFAREREDUCERDB
CHARACTER SET utf8 COLLATE utf8_general_ci;

/* ****************************************************************************** */
/* ******************************** CREATE TABLE ******************************** */

CREATE TABLE IF NOT EXISTS SWFAREREDUCERDB.UPCOMING_FLIGHTS (
UPCOMING_FLIGHT_ID			INT(11) NOT NULL AUTO_INCREMENT,
CONFIRMATION_NUM			VARCHAR(6) NOT NULL,
FIRST_NAME					VARCHAR(255) NOT NULL,
LAST_NAME					VARCHAR(255) NOT NULL,
EMAIL						VARCHAR(255) NOT NULL,
ORIGIN_AIRPORT_CODE     	VARCHAR(3) DEFAULT NULL,
DESTINATION_AIRPORT_CODE	VARCHAR(3) DEFAULT NULL,
DEPART_DATE					VARCHAR(7) DEFAULT NULL,
DEPART_TIME					VARCHAR(7) DEFAULT NULL,
ARRIVE_DATE					VARCHAR(7) DEFAULT NULL,
FLIGHT_NUM					VARCHAR(9) DEFAULT NULL,
PAID_DOLLARS				VARCHAR(6) NOT NULL DEFAULT '0',
PAID_POINTS					VARCHAR(6) NOT NULL DEFAULT '0',
SUBMISSION_DATE				TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (UPCOMING_FLIGHT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='UPCOMING FLIGHTS' AUTO_INCREMENT=100000;

/* ***************************************************************************** */
/* ******************************** INSERT INTO ******************************** */

INSERT INTO SWFAREREDUCERDB.UPCOMING_FLIGHTS (CONFIRMATION_NUM,FIRST_NAME,LAST_NAME,EMAIL,ORIGIN_AIRPORT_CODE,DESTINATION_AIRPORT_CODE,DEPART_DATE,DEPART_TIME,ARRIVE_DATE,FLIGHT_NUM,PAID_DOLLARS,PAID_POINTS) VALUES ('8ABYGC','Lorenzo','Javier','9252007284@vtext.com','SJC','PHX','10/02/2015','8:05PM','9:50PM','179','0','4291');
INSERT INTO SWFAREREDUCERDB.UPCOMING_FLIGHTS (CONFIRMATION_NUM,FIRST_NAME,LAST_NAME,EMAIL,ORIGIN_AIRPORT_CODE,DESTINATION_AIRPORT_CODE,DEPART_DATE,DEPART_TIME,ARRIVE_DATE,FLIGHT_NUM,PAID_DOLLARS,PAID_POINTS) VALUES ('8ABYGC','Lorenzo','Javier','9252007284@vtext.com','PHX','SJC','10/06/2015','5:40AM','7:35AM','2787','0','2989');
INSERT INTO SWFAREREDUCERDB.UPCOMING_FLIGHTS (CONFIRMATION_NUM,FIRST_NAME,LAST_NAME,EMAIL,ORIGIN_AIRPORT_CODE,DESTINATION_AIRPORT_CODE,DEPART_DATE,DEPART_TIME,ARRIVE_DATE,FLIGHT_NUM,PAID_DOLLARS,PAID_POINTS) VALUES ('HHGRHL','Lorenzo','Javier','9252007284@vtext.com','SJC','ONT','10/30/2015','8:20PM','9:30PM','2953','0','6798');
INSERT INTO SWFAREREDUCERDB.UPCOMING_FLIGHTS (CONFIRMATION_NUM,FIRST_NAME,LAST_NAME,EMAIL,ORIGIN_AIRPORT_CODE,DESTINATION_AIRPORT_CODE,DEPART_DATE,DEPART_TIME,ARRIVE_DATE,FLIGHT_NUM,PAID_DOLLARS,PAID_POINTS) VALUES ('HN9RRZ','Lorenzo','Javier','9252007284@vtext.com','LAX','SJC','11/02/2015','8:45AM','9:55AM','1147','0','3184');
INSERT INTO SWFAREREDUCERDB.UPCOMING_FLIGHTS (CONFIRMATION_NUM,FIRST_NAME,LAST_NAME,EMAIL,ORIGIN_AIRPORT_CODE,DESTINATION_AIRPORT_CODE,DEPART_DATE,DEPART_TIME,ARRIVE_DATE,FLIGHT_NUM,PAID_DOLLARS,PAID_POINTS) VALUES ('832STR','Lorenzo','Javier','9252007284@vtext.com','SJC','PHX','11/04/2015','6:35AM','9:20AM','539','0','2989');
INSERT INTO SWFAREREDUCERDB.UPCOMING_FLIGHTS (CONFIRMATION_NUM,FIRST_NAME,LAST_NAME,EMAIL,ORIGIN_AIRPORT_CODE,DESTINATION_AIRPORT_CODE,DEPART_DATE,DEPART_TIME,ARRIVE_DATE,FLIGHT_NUM,PAID_DOLLARS,PAID_POINTS) VALUES ('8J9T7V','Danielle','Gonzalez','9095698490@txt.att.net','ONT','SJC','09/03/2015','6:45PM','7:50PM','3243','60','0');
INSERT INTO SWFAREREDUCERDB.UPCOMING_FLIGHTS (CONFIRMATION_NUM,FIRST_NAME,LAST_NAME,EMAIL,ORIGIN_AIRPORT_CODE,DESTINATION_AIRPORT_CODE,DEPART_DATE,DEPART_TIME,ARRIVE_DATE,FLIGHT_NUM,PAID_DOLLARS,PAID_POINTS) VALUES ('H9CRR8','Giovanni','Javier','9257856233@vtext.com','OAK','ONT','10/30/2015','8:40AM','9:55AM','2751','0','3803');
INSERT INTO SWFAREREDUCERDB.UPCOMING_FLIGHTS (CONFIRMATION_NUM,FIRST_NAME,LAST_NAME,EMAIL,ORIGIN_AIRPORT_CODE,DESTINATION_AIRPORT_CODE,DEPART_DATE,DEPART_TIME,ARRIVE_DATE,FLIGHT_NUM,PAID_DOLLARS,PAID_POINTS) VALUES ('H38RR6','Giovanni','Javier','9257856233@vtext.com','LAX','OAK','11/02/2015','9:15AM','10:30AM','2906','0','3184');
-- INSERT INTO SWFAREREDUCERDB.UPCOMING_FLIGHTS (CONFIRMATION_NUM,FIRST_NAME,LAST_NAME,EMAIL,ORIGIN_AIRPORT_CODE,DESTINATION_AIRPORT_CODE,DEPART_DATE,DEPART_TIME,ARRIVE_DATE,FLIGHT_NUM,PAID_DOLLARS,PAID_POINTS) VALUES ();

/* ********************************** COMMIT ********************************** */

COMMIT WORK;

/* ****************************************************************************** */